In [101]:
import pandas as pd
import numpy as np

In [147]:
def load_and_process(filePathCSV):
    df1 = (pd.read_csv(filePathCSV)
           .drop(['TOI/GP','FOW%','S%'], axis=1)
           .rename(columns = {'GP':'GamesPlayed' , '+/-':'PlusMinus', 'PIM':'PenaltyMins', 'S':'Shots'})
    )
    df2 = (df1 
           .loc[lambda x: x['Shots']>50]
           .loc[lambda x: x['GamesPlayed']>70]
    )
    return df2

In [148]:
load_and_process('FlamesData.csv')

,Player,S/C,Pos,GamesPlayed,G,A,P,PlusMinus,PenaltyMins,P/GP,EVG,EVP,PPG,PPP,SHG,SHP,OTG,GWG,Shots
3,Tommy Albelin,L,D,339.0,12.0,59.0,71.0,-10.0,92.0,0.21,6.0,38.0,5.0,27.0,1.0,6.0,1.0,3.0,382.0
6,Tony Amonte,L,R,161.0,24.0,48.0,72.0,-1.0,83.0,0.45,18.0,48.0,4.0,20.0,2.0,4.0,0.0,4.0,294.0
9,Rasmus Andersson,R,D,160.0,7.0,34.0,41.0,8.0,84.0,0.26,7.0,35.0,0.0,6.0,0.0,0.0,0.0,0.0,247.0
12,Adrian Aucoin,R,D,157.0,20.0,49.0,69.0,5.0,83.0,0.44,12.0,36.0,8.0,32.0,0.0,1.0,1.0,4.0,247.0
13,Anton Babchuk,R,D,104.0,10.0,28.0,38.0,19.0,26.0,0.37,3.0,23.0,6.0,14.0,1.0,1.0,0.0,2.0,140.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,Clarke Wilm,L,C,303.0,31.0,42.0,73.0,-7.0,250.0,0.24,20.0,58.0,5.0,9.0,6.0,6.0,0.0,0.0,343.0
480,Carey Wilson,R,C,355.0,102.0,161.0,263.0,33.0,160.0,0.74,77.0,208.0,20.0,46.0,5.0,9.0,1.0,13.0,613.0
487,Trent Yawney,L,D,274.0,11.0,45.0,56.0,20.0,368.0,0.20,8.0,35.0,2.0,18.0,1.0,3.0,0.0,1.0,227.0
489,Stephane Yelle,L,C,339.0,31.0,65.0,96.0,2.0,174.0,0.28,22.0,72.0,6.0,17.0,3.0,7.0,0.0,5.0,407.0
491,Zarley Zalapski,L,D,178.0,21.0,55.0,76.0,7.0,220.0,0.43,12.0,48.0,9.0,28.0,0.0,0.0,0.0,4.0,309.0

In [102]:
FData = pd.read_csv('FlamesData.csv')

In [103]:
FData.head()

,Player,S/C,Pos,GP,G,A,P,+/-,PIM,P/GP,...,PPG,PPP,SHG,SHP,OTG,GWG,S,S%,TOI/GP,FOW%
0,Rick Adduono,L,C,3.0,0.0,0.0,0.0,-1.0,2.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,--,--
1,Kenny Agostino,L,L,10.0,1.0,1.0,2.0,-4.0,0.0,0.20,...,0.0,0.0,0.0,0.0,0.0,0.0,15.0,6.7,11:35,--
2,Peter Ahola,L,D,2.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,--,--
3,Tommy Albelin,L,D,339.0,12.0,59.0,71.0,-10.0,92.0,0.21,...,5.0,27.0,1.0,6.0,1.0,3.0,382.0,3.1,--,0
4,Akim Aliu,R,R,7.0,2.0,1.0,3.0,1.0,26.0,0.43,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,40,10:55,--