In [15]:
import pandas as pd

In [14]:
FlamesData = pd.read_csv('FlamesData.csv')

In [16]:
FlamesData.head()

,Player,S/C,Pos,GP,G,A,P,+/-,PIM,P/GP,...,PPG,PPP,SHG,SHP,OTG,GWG,S,S%,TOI/GP,FOW%
0,Rick Adduono,L,C,3,0,0,0,-1,2,0.00,...,0,0,0,0,0,0,1,0,--,--
1,Kenny Agostino,L,L,10,1,1,2,-4,0,0.20,...,0,0,0,0,0,0,15,6.7,11:35,--
2,Peter Ahola,L,D,2,0,0,0,0,0,0.00,...,0,0,0,0,0,0,1,0,--,--
3,Tommy Albelin,L,D,339,12,59,71,-10,92,0.21,...,5,27,1,6,1,3,382,3.1,--,0
4,Akim Aliu,R,R,7,2,1,3,1,26,0.43,...,0,0,0,0,0,0,5,40,10:55,--